todo_manager/todo_list/urls.py
from django.views.generic import TemplateView
from django.urls import path

from . import views

app_name = 'todo_list'

urlpatterns = [
    # path("", views.index_view(), name = 'index'),
    # path("", views.ToDoListIndexView.as_view(), name = 'index'),
    path("", views.ToDoListView.as_view(), name="index")
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path("todos/", include("todo_list.urls")),
]

todo_manager/todo_list/models.py
from django.db import models

# Create your models here.
class ToDoItem(models.Model):
    class Meta:
        ordering = "id",
        verbose_name_plural = 'ToDo Items'
    title = models.CharField(max_length=250)
    Done = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo_manager/todo_list/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import ToDoItem
from django.views.generic import TemplateView, ListView

def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = ToDoItem.objects.all()
    return render(request,
                   "todo_list/index.html",
                   context={"todo_items": todo_items})

class ToDoListIndexView(TemplateView):
    template_name = 'todo_list/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_items"] = ToDoItem.objects.all()
        return context

class ToDoListView(ListView):
    template_name = 'todo_list/index.html'
    model = ToDoItem

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        Base Title
        {% endblock title %}</title>
</head>
<body>

    {% include "components/navbar.html" %}
    
    {% block body %}
        Base body
    {% endblock body %}


    <footer>
        &copy; Django TODO App
        {% block footer %}
            
        {% endblock footer %}
    </footer>


</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'todo_list:index' %}">Todos</a></li>
        <li><a href="#">About</a></li>
    </ul>
</nav>

todo_manager/templates/index.html
{% extends "base.html" %}

{% block title %}
    TODO App Index
{% endblock title%}

{% block body %}
    <h1>TODO App</h1>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends "base.html" %}

{% block footer %}
    ToDo List
{% endblock footer %}

todo_manager/todo_list/templates/todo_list/index.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo List App
{% endblock title %}

{% block body %}
    <h1>ToDo List App</h1>
    <h2>ToDos:</h2>
    <ul>
        {% for todo_item in object_list  %}

        <li>
            {{ todo_item.title }}
            {% if todo_item.Done %}
            ✅
            {% else %}
            ❌
            {% endif %}
        </li>

        {% endfor %}
    </ul>
{% endblock body %}